### ISSUE TITLE
Fails with Ember CLI 2.11

### ISSUE THREAD

**Issue by mfeckie** [healthsparq/ember-fountainhead#17]
Ember CLI 2.11. no longer includes ember through `bower.json`, this results in the `ember-template-compiler.js` file not being found.

The file would now be part of `ember-source`, though I'm unsure how to include files from there .

**Comment by evrowe** [comment]
Yeah, that was a pretty big change that landed in 2.11. We're still on 2.10 for our production app internally but will be upgrading to 2.11 sometime in the next couple of weeks.

Obviously this addon will need to have support for 2.11 before we can make that update for our own app, so we'll be looking into creating a new release that is compatible with 2.11 sometime in the coming week.

Thanks for filing this!

**Comment by mfeckie** [comment]
I've had a look at it locally and hacked my own version to make it work.

I did this by loading the template compiler via `app.import('vendor/ember-template-compiler.js);` in `index.js` and including it myself.

I used this version of the templates compiler `https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.11.0/ember-template-compiler.js`

I'm not sure that helps with a long term solution, but may be a useful hack for others in the interim

**Comment by evrowe** [comment]
@mfeckie Yeah that's an alright temporary workaround if you really need to use it right away against a CLI 2.11 app but we need to find a way to properly include it from a real dependency.

The template compiler is still included as part of the `ember-source` npm package, we just need to spend a little time researching how to properly import it. It _should_ be pretty easy to deal with (hopefully).

We'll keep you posted!

**Comment by mfeckie** [comment]
I'll also do some poking around as it's piqued my curiosity, I'll share anything useful I discover

**Comment by DHedgecock** [comment]
@mfeckie this should now be fixed in 2.2.0.

We're directly importing the template compiler from NPM, which didn't work before, but appears to work now. If you still have issues please reopen. Thanks.
