### ISSUE TITLE
Prebuild `docs` does not respect build environment

### ISSUE THREAD

**Issue by DHedgecock** [healthsparq/ember-fountainhead#9]
Running a prod build in repo runs the `docs` command, but a dev build is run.

The prebuild `docs` command needs to pass the build env to the docs generation so that production builds generate the create documentation.

**Comment by bigmoves** [comment]
Ah that's a good catch. Should be easy to fix.

**Comment by evrowe** [comment]
I think this is resolved at this point, yeah? Can we close this or does it need more work?

**Comment by DHedgecock** [comment]
Not quite, Ember uses a `process.env.EMBER_ENV` instead of `process.env.NODE_ENV` and of course it isn't setup until later in the build process. 😑 

```
⇒  ember b -environment=production
env:  development <- From fountainhead.js
cleaning up...
Built project successfully. Stored in "dist/".
...
```

I'm going to experiment with making the configuration file work just like Webpack's, where you can export an object or a function and the function receives the env:

`module.exports = function(env) { ... }`

This is actually more of an enhancement than a bug. The environment in the configs was always being pulled from the `NODE_ENV` which we were manually setting when running `ember docs`.

**Comment by DHedgecock** [comment]
Fixed in dev branch.
